### ISSUE TITLE
website is unsafe

### ISSUE THREAD

**Issue by plijnzaad** [shawnzhangyx/PePr#13]
When I try to follow the link to the [wiki](https://ones.ccmb.med.umich.edu/wiki/PePr/) using firefox, I get "The owner of ones.ccmb.med.umich.edu has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
Advanced info: ssl_error_no_cypher_overlap" and if I insist, firefox says: "ones.ccmb.med.umich.edu uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe." Maybe something to look into (maybe particular to firefox,  chrome and safari are fine with it ...)

**Comment by shawnzhangyx** [comment]
Thanks for pointing this out! I have no idea why the website encryption is not compatible with firefox, but seems to work well with Chrome and Safari...Eventually I will migrate the website onto another sever, but for now,  I'm working on a PDF version of the user manual. Will update on this issue once it is done.

**Comment by shawnzhangyx** [comment]
I have moved the tutorial to README.md in this repository. Will make a PDF file out of it sometime.
