### ISSUE TITLE
chip3 and input3 parameters adding

### ISSUE THREAD

**Issue by mictadlo** [shawnzhangyx/PePr#17]
Hi,
I have 3 replicates and I used 7 different antibodies. Furthermore, each replicate contains C(1-7) and CL(1-7) datasets. CL(1-7) has been treated with chemicals whereas C(1-7) was not treated. 

![Imgur](http://i.imgur.com/JRRwVq6.png)

I think, I need chip3 and input3 parameters in order to do my analyse my data. Could you please add chip3 and input3 parameters?

Thank you in advance.

Best wishes,

Mic

**Comment by shawnzhangyx** [comment]
Hi Mic, 

PePr can only do group comparisons between 2 conditions, therefore cannot support 3 groups. If you meant putting three replicates in one group, I believe you can do it by separating your file (replicate) names by comma. 

Best,
Yanxiao
