### ISSUE TITLE
ImportError: No module named PePr

### ISSUE THREAD

**Issue by AlicePsyche** [shawnzhangyx/PePr#19]
Hi, 

I upgraded PePr to 1.1.12 then I failed loading the package...

```bash
pip install PePr
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.14.0 in /lib/python2.7/site-packages (from PePr)
Requirement already satisfied (use --upgrade to upgrade): sharedmem in /lib/python2.7/site-packages (from PePr)
Requirement already satisfied (use --upgrade to upgrade): pysam in /lib/python2.7/site-packages (from PePr)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.0 in /lib/python2.7/site-packages (from PePr)
Installing collected packages: PePr
Successfully installed PePr-1.1.12
```
There is PePr in my bin folder but when I run `PePr --version`

```bash
Traceback (most recent call last):
  File "/bin/PePr", line 7, in <module>
    from PePr.PePr import argless_main
ImportError: No module named PePr
```

I checked the PePr package path and it is in my $PYTHONPATH so I have no clue why this happened...

Thanks in advance.

**Comment by shawnzhangyx** [comment]
That is strange. If you go into the package path and call `python PePr.py` directly from that folder, would it work? 
Also, are you familiar with virtualenv? I suggest trying to install and run PePr within virtualenv.

Let me know how it goes. 

Best,
Yanxiao

**Comment by AlicePsyche** [comment]
OH ! `python PePr.py` could work. I can just use this method for emergency.

```bash

$ python PePr.py
Usage: Basic usage: PePr.py -c chip_files -i input_files -f file_type
You could also use a parameter file by: PePr.py -p param_file
For pre-processing only (parameter estimation), run: PePr-preprocess
For post-processing, run: PePr-postprocess
```

Sorry, I am new to python, usually use conda to manage packages... I would try virtualenv as you suggested. Does this result from some kind of package conflicts? Anyway, Thanks for your help, at least I can run the program now  :)

**Comment by shawnzhangyx** [comment]
I'm glad it's working. It may have to do with the python path that you have set, so python cannot find PePr. Do you have two instances of PePr installed? Maybe that will create a conflict.

**Comment by AlicePsyche** [comment]
I do have PePr 1.0.9 installed before but I have uninstall it. How could I fix this problem ?

**Comment by shawnzhangyx** [comment]
I am not sure if this will work, but try this. put the newer PePr (1.1.12) path pior to other python paths in your .bashrc/.bash_profile file, such as `export PYTHONPATH=PePr_path:$PYTHONPATH`. `PePr_path` is the path to PePr but not including the PePr directory. For example, `..../lib/python2.7/site-packages/`.
