### ISSUE TITLE
PePr differential binding analysis killed

### ISSUE THREAD

**Issue by nam10san** [shawnzhangyx/PePr#20]
I am new to PePr and I am running the following command in my Ubuntu for differential binding analysis:
python PePr.py -c H3K27ac_1_diseased_heart_mm9_sorted.bam,H3K27ac_2_diseased_heart_mm9_sorted.bam -i Input_1_diseased_heart_mm9_sorted.bam,Input_2_diseased_heart_mm9_sorted.bam --chip2 H3K27ac_1_Normal_heart_mm9_sorted.bam,H3K27ac_2_Normal_heart_mm9_sorted.bam,H3K27ac_3_Normal_heart_mm9_sorted.bam --input2 Input_1_Normal_heart_mm9_sorted.bam,Input_2_Normal_heart_mm9_sorted.bam,Input_3_Normal_heart_mm9_sorted.bam -f bam --diff --normalization intra-group --keep-max-dup 1 --name H3K27ac_heart_diseased_vs_Normal 
Everything went fine with estimation of shift size and normalization constants. Then it said Begin differential binding analysis and then killed. I did not stop it myself and I dont understand why the process got killed by itself. Can you guide me what could be the problem? 
[H3K27ac_heart_diseased_vs_Normal__PePr_parameters.txt](https://github.com/shawnzhangyx/PePr/files/384107/H3K27ac_heart_diseased_vs_Normal__PePr_parameters.txt)

**Comment by shawnzhangyx** [comment]
What is your computer configuration (especially RAMs) and file sizes? It could be that there is not enough memory for it if you're running other programs at the same time.

**Comment by nam10san** [comment]
Hello all,
   Thanks a lot for your reply. I think you are right. I am using Ubuntu parallel to my Windows. My computer has 8 GB where 5 GB is allotted for base memory for Ubuntu. The files are 14 GB which is mounted from a hard disk. I will see if I can increase the memory of Ubuntu and check if that works. Thanks a lot.

Sankari.

**Comment by shawnzhangyx** [comment]
Yeah try something like ~8Gb (although normally it would not use that much memory but it depends on data). Let me know if you're still experiencing the same problem.

**Comment by nam10san** [comment]
It worked great when I added 7 GB RAM. I got the bed files with chip1 and chip2. Thanks a lot for your great help.

Sankari.
