### ISSUE TITLE
bioconda release

### ISSUE THREAD

**Issue by jasper1918** [shawnzhangyx/PePr#24]
Hi - I have been using pepr with good results and am curious if you will be updating the bioconda recipe with a newer release or if your preferred mechanism is through pypi. I'm good either way but am using the bioconda recipe for new VM builds currently.

**Comment by shawnzhangyx** [comment]
Thank you for your information and thanks for using our software! I'm on a vacation right now, will get back to you after I return next month.

**Comment by shawnzhangyx** [comment]
Hello, 

I will try to update the bioconda recipe to the latest version of pepr. Will let you know if I succeed.

**Comment by shawnzhangyx** [comment]
I have updated PePr to the latest version (v1.1.18) on bioconda-recipe.
