### ISSUE TITLE
Running PePr with Input and IgG controls

### ISSUE THREAD

**Issue by frymor** [shawnzhangyx/PePr#28]
Is it possible to run PePr with two controls simultaneously?
We have an time-course Experiment with an Ip and both input and IgG samples for each time point. Is it possible to run the peak calling for both tools with one run?

If so - are these the `input1` and `input2` parameters?
How will the normalisation than work, when I have "three conditions"?
thanks

**Comment by shawnzhangyx** [comment]
Hi, 
Pasted from my email response:
PePr does not simultaneously consider two input samples ( I don't think any of the existing tools could do that either). But you could run PePr on each of the control ( Input or IgG) and use the peaks that overlap.
