### ISSUE TITLE
array init fails in Python3

### ISSUE THREAD

**Issue by ptrebert** [shawnzhangyx/PePr#30]
Hi,
I am running PePr 1.1.18 in a Python 3.6 Conda environment. The array init in the quoted line fails due to the changed default behaviour of the division operator (returning a float here, but integer is needed).

https://github.com/shawnzhangyx/PePr/blob/758f18d69f249e43211e837d90ad24d73d171c63/PePr/pre_processing/cal_normalization.py#L410
```
TypeError: integer argument expected, got float
```
Best,
Peter

**Comment by shawnzhangyx** [comment]
Hi Peter, 
Sorry for not getting back to you earlier! I was in a conference the last few days. 
Thanks for catching the bug, I will fix it as soon as I get back. 

Thanks,
Shawn

**Comment by shawnzhangyx** [comment]
Hi Peter, 
I have patched it (v1.1.24) and submitted a pull request to bioconda recipes. Will wait for them to integrate the changes. Meanwhile if you're interested, you could install the patched version from pypI or github. 

Thank you!
Shawn

**Comment by ptrebert** [comment]
Hi Shawn,
thanks for fixing - I solved my problem by simply using the Python2 version of PePr. I'll switch back as soon as the Conda version is ready. Thanks.
Best,
Peter

**Comment by shawnzhangyx** [comment]
Great! Conda accepted the latest version of the PePr. It may appear soon. Let me know how it works. 
Best,
Shawn
