### ISSUE TITLE
Omicspedia Unreachable

### ISSUE THREAD

**Issue by aakashsur** [shawnzhangyx/PePr#32]
It looks like this site (https://omicspedia.ucsd.edu/omicspedia/tags/PePr/) mentioned in the README is unreachable.

![image](https://user-images.githubusercontent.com/7614271/38761543-99526872-3f38-11e8-9f5b-f9060304ca31.png)

**Comment by shawnzhangyx** [comment]
Thanks for pointing this out. I failed to maintain the OMICSPEDIA site for a while. I will update the link.

**Comment by shawnzhangyx** [comment]
New link at https://renlab.sdsc.edu/omics/
