### ISSUE TITLE
PePr pooling of replicates or individual calling of peaks

### ISSUE THREAD

**Issue by abhisheksinghnl** [shawnzhangyx/PePr#34]
Hi,

I am bit confused with the working of PePr, could you please enlighten me.

When I use the complete pipeline like follows:

` PePr -c  H3k4me1.P1.bam,H3k4me1.P2.bam,H3k4me1.P3.bam -i input.bam  -n H3K4me1 -f bam --peaktype broad `

my question, will the samples be pooled before peak calling? or peaks will be pooled or what? 

Like Macs, when it takes the replicates, it pools the replicates and calls peaks. 

Kindly answer.

thank you

**Comment by shawnzhangyx** [comment]
It does not pool replicates, rather it treats each replicate as a separate sample, and estimate variance from the replicates. PePr will try to call peaks that are consistently enriched in both(or all if >2) replicates. Is it clearer?

**Comment by abhisheksinghnl** [comment]
Hi,

thank you for your reply.

It clears all the doubts.

Best regard

**Comment by shawnzhangyx** [comment]
You're welcome. Closing the ticket.
