### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by apteryks** [shawnzhangyx/PePr#36]
Hi!

The source code https://github.com/shawnzhangyx/PePr/blob/master/PePr/__init__.py indicates the version string as `1.1.24`, while the latest tag is `1.1.18`.  Are some tags missing, or I am missing something? :-)

Thank you!

**Comment by shawnzhangyx** [comment]
Hi thanks for catching this. The newest version indeed is 1.1.24. but I did not update the tag. Thank you!
