### ISSUE TITLE
Modify setup.py a bit

### ISSUE THREAD

**Issue by rjeschmi** [shawnzhangyx/PePr#9]
Hi, thanks for the software, I had some suggestions to make installation a bit easier.

When I have setuptools installed it will try to build these packages as eggs rather than directories and that makes finding PePr.py a bit hard. 

I modified my forked version to create an "entry_point" that calls a new wrapper function in PePy.py and setuptools will put the script PePr in your bin directory.

If you are interested I can Pull Request this change.

I'd also suggest tagging a release so it is easier to download a specific tarball.

Thanks again!

**Comment by shawnzhangyx** [comment]
Hi, thanks for making changes to the package! Yes of course this will be a good functionality to add, so please create a Pull Request for this changes. Thanks very much!

Best,
Yanxiao

**Comment by rekado** [comment]
I agree about these two points.  Currently, after installation PePr is installed as an egg archive.  I packaged PePr for the GNU Guix package manager and applied this change to `setup.py`:

~~~
- from setuptools import setup
+ from distutils.core import setup
~~~

This disables the generation of an egg archive and installs the files to `$prefix/lib/python2.7/site-packages`.

I would also like to suggest to tag future releases, especially if future releases won't be published on pypi as well.  Currently, I'm using the latest tarball from pypi.

**Comment by shawnzhangyx** [comment]
@rekado Thanks for the advice! I tried to switch to distutils.core but it still only installs the egg file. The only way to install the whole directory structures seems to be using 'pip install PePr.X.X.X.tar.gz'. 

I have all release tarballs in the /dist directory. Tagging every release on github seems cumbersome as it has to include every files (even every tarballs). I will publish all future releases on pypi.
